spring.application.name=gasmapocho
# Servidor
server.port=8080

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bd_gasmapocho?useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=Trabajo
spring.datasource.password=vPqfh74Kdqo)8A3Qsl(

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# silenciar el otro warning:
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false
